apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: s3-repo
  namespace: demo
spec:
  backend:
    s3:
      bucket: stash-backup
      prefix: demo
    storageSecretName: s3-secret
  retentionPolicy:
    name: "keep-last-10"
    keepLast: 10
    prune: true
