apiVersion: stash.appscode.com/v1beta2
kind: BackupConfiguration
metadata:
  name: mariadb-backup
  namespace: demo
spec:
  driver: Restic
  repository:
  - name: gcs-repo
  target:
    alias: sample-mariadb
    ref:
      apiVersion: apps/v1
      kind: StatefulSet
      name: sample-mariadb
    sidecar:
      functionName: maria-backup
      params:
        a: b
        c: d
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
