apiVersion: stash.appscode.com/v1beta2
kind: BackupConfiguration
metadata:
  name: mariadb-backup
  namespace: demo
spec:
  driver: Restic
  target:
    alias: sample-mariadb
    ref:
      apiVersion: apps/v1
      kind: StatefulSet
      name: sample-mariadb
  sessions:
  - name: full-backup-to-gcs-s3
    type: full-backup
    schedule: "0 0 * * *"
    repositories:
    - gcs-repo
    - s3-repo
    verify:
      schedule: "0 0 * * *"
      verifier: maria-backup-verify-full
      params:
      - name: releaseName
        value: sample-mariadb
  - name: incremental-backup-to-gcs
    type: incremental-backup
    schedule: "*/15 * * *"
    repositories:
    - gcs-repo
    verify:
      schedule: "*/45 * * * *"
      verifier: maria-backup-verify-quick
      params:
      - name: releaseName
        value: sample-mariadb
