apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: sample-postgres-restore
  namespace: demo
  labels:
    kubedb.com/kind: Postgres
spec:
  task:
    name: postgres-restore-12.4.0
  repository:
    name: s3-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: sample-postgres
  rules:
    - snapshots: [latest]
