apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: backup-hook-demo
  namespace: demo
spec:
  schedule: "*/5 * * * *"
  task:
    name: mysql-backup-8.0.14
  repository:
    name: gcs-repo
  hooks:
    preBackup:
      exec:
      - /bin/sh
      - -c
      - mysql -u root --password=$MYSQL_ROOT_PASSWORD -h sample-mysql.demo.svc -p 3366 -e "SET GLOBAL super_read_only = ON;"
      executor:
        functionName: mysql-hook-executor
        params:
          a: b
          c: d
  target:
    ref:
      apiVersion: apps/v1
      kind: StatefulSet
      name: sample-sts
  retentionPolicy:
    name: keep-last-5
    keepLast: 5
    prune: true
