apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: gcs-repo
  namespace: backup
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: /demo/cross-namespace/sample-mysql
    storageSecretName: gcs-secret
  usagePolicy:
    allowedNamespaces:
      from: All