apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: mysql-restore
  namespace: staging
spec:
  repository:
    name: gcs-repo
    namespace: backup
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mysql-recovery
  rules:
    - snapshots: [latest]